name: Publish package to the Maven Central Repository
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
      - run: sudo apt update
      - run: sudo apt install inotify-tools
      - run: inotifywait -mr /home/runner/work/Mybatis-PageHelper/Mybatis-PageHelper/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
      - run: touch starting_publish_uses-checkout_9
      - run: rm starting_publish_uses-checkout_9
      - uses: actions/checkout@v3
      - run: touch starting_publish_SetupMavenCentralRepository_10
      - run: rm starting_publish_SetupMavenCentralRepository_10
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - run: touch starting_publish_Publishpackage_23
      - run: rm starting_publish_Publishpackage_23
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -P release clean deploy
      - run: touch starting_finished_finished_8979874
        if: always()
      - run: rm starting_finished_finished_8979874
        if: always()
      - name: Execute py script # run file
        if: always()
        run: |
          python .github/workflows/script.py
      - name: Pushes analysis to another repository
        if: always()
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'optimizing-ci-builds-ci-analysis'
          destination-github-username: 'UT-SE-Research'
          destination-repository-name: 'ci-analyzes'
          target-branch: '1676606676-d8dc3b1'
          target-directory: 'Mybatis-PageHelper/.github/workflows/release/publish'
        continue-on-error: true
      - name: Check push directory exit code
        if: steps.push_directory.outcome == 'failure'
        run: |
          echo 'push failed, trying pull and then push'
          git stash
          git pull
          git stash apply
          while ! git push origin {time}; do
            git push
          done